version: '3.8'

services:
  web:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - uploads:/app/uploads
    restart: always

volumes:
  uploads:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /mnt/md0/network_drive/photos
